<?php

namespace Arii\ATSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlarmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlarmsRepository extends EntityRepository
{

    public function findByNote($note_id) {        
        // On recherche la doc la plus proche
        return  $this->createQueryBuilder('o')
               ->Where(':note = o.note') 
               ->setParameter('note', $note_id)    
               ->getQuery()
               ->getResult();
    }

}
