<?php

namespace Arii\ATSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotesRepository extends EntityRepository
{
    public function findByJobName($job) {        
        // On recherche la doc la plus proche
        return  $this->createQueryBuilder('o')
                ->Where(':template LIKE o.job_name') 
                ->setParameter('template', $job)                  
               ->getQuery()
               ->getResult();
    }
    
}
